---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp css/styles.css $DEPLOYPATH
    - /bin/cp css/galeria.css $DEPLOYPATH
    - /bin/cp css/captcha.css $DEPLOYPATH